version: '3'

services:
  blogs:
    build: ./blogs
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./blogs:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: bigjoe11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

