services:
  blogs:
    build: ./flask_blog/blogs
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./flask_blog/blogs:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: bigjoe11
    volumes:
      - ./postgres-blog-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"