app:
  working_dir: /home/web/flask/flask_blog/blogs
  build: .
  command: python app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    -db
db:
  image: postgres
  restart: always
  enviornment:
    POSTGRES_PASSWORD: bigjoe11
  volumes:
    - ./postgres-blog-data:/var/lib/postgresql/data
  port:
    - 5432:5432