app:
  build:
    context: ./blogs
    dockerfile: Dockerfile
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: bigjoe11
  volumes:
    - ./postgres-blog-data:/var/lib/postgresql/data
  ports:
    - "5432:5432"